= ADET: Autorizacion de Trabajo

Software Web para gestion de Autorizaciones de diversas empresas.

Este proyecto comenzó a principios de 2019, en la ciudad de Neuquén, capital de la provincia de Neuquén, Argentina. Es un proyecto académico que se realizó para la materia "Practica Profesionalizante II" del Institituto de Formación y Educación Superior (IFES). Se basa en el modelo Domain-Driven Desing (DDD) y su implementación es en Java utilizando el framework Apache ISIS y Apache Shiro para la seguridad.

El Software permite crear, listar y gestionar autorizaciones de distintas empresas, cada uno con su respectiva hora registrada y participantes involucrados.

== Quick start

Clone proyecto en directorio a eleccion:
[source,bash]
----
git clone https://github.com/proyecto-ifes-autorizacion/AdeT.git
----

Luego compile el proyecto:

[source,bash]
----
mvn clean install
----

Inicialize:

[source,bash]
----
mvn -pl webapp jetty:run
----

Loguearse usando: 

* usuario: `isis-module-security-admin`
* contraseña: `pass`


== Estructura de Aplicacion

La siguiente table explica los contenidos de cada uno de los directorios:

[width="100%",options="header,footer", cols="2a,4a"]
|====================
|Directorio
|Descripcion

|`application`
|Define clases a nivel aplicacion tales como menues y el "AppManifest" (el cual define los modulos que componen la aplicacion).
Tambien contiene pruebas de integraciones de toda la aplicacion como especificaciones de BDD

|`module-simple`
|Contiene el modulo "simple", consistiendo de la entidad "SimpleObject" y correspondiente repositorio, ademas de pruebas de integraciones y unidad-especifica-de-modulo.
Ademas, corre la meta 'isis:validate' para los objetos de dominio dentro del modulo.

|`webapp`
|Asiembla la aplicacion dentro de una aplicacion web (conteniendo tanto el visualizador Wicket y visualizador de Objetos Restful) y dentro de una imagen docker, y tambien corre la meta 'isis:swagger'


